// <auto-generated />
using BeepBong;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BeepBong.Migrations
{
    [DbContext(typeof(BeepBongContext))]
    [Migration("20190316033205_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854");

            modelBuilder.Entity("BeepBong.Models.Programme", b =>
                {
                    b.Property<int>("ProgrammeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AudioComposer");

                    b.Property<string>("Channel");

                    b.Property<string>("Name");

                    b.Property<string>("Year");

                    b.HasKey("ProgrammeId");

                    b.ToTable("Programmes");
                });

            modelBuilder.Entity("BeepBong.Models.Sample", b =>
                {
                    b.Property<int>("SampleId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("BitRate");

                    b.Property<int>("Channels");

                    b.Property<string>("Checksum");

                    b.Property<int?>("Compression");

                    b.Property<string>("Duration");

                    b.Property<string>("SampleRate");

                    b.Property<int>("TrackId");

                    b.HasKey("SampleId");

                    b.HasIndex("TrackId");

                    b.ToTable("Samples");
                });

            modelBuilder.Entity("BeepBong.Models.Track", b =>
                {
                    b.Property<int>("TrackId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("ProgrammeId");

                    b.Property<string>("Subtitle");

                    b.HasKey("TrackId");

                    b.HasIndex("ProgrammeId");

                    b.ToTable("Tracks");
                });

            modelBuilder.Entity("BeepBong.Models.Sample", b =>
                {
                    b.HasOne("BeepBong.Models.Track", "Track")
                        .WithMany("Samples")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BeepBong.Models.Track", b =>
                {
                    b.HasOne("BeepBong.Models.Programme", "Programme")
                        .WithMany("Tracks")
                        .HasForeignKey("ProgrammeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
